### ISSUE TITLE
Problems updating to 0.4.0.0

### ISSUE THREAD

**Issue by jamesaoverton** [NotBrianZach/patchedPostgrest#1]
Thank you very much for sharing this bit of code! I'm new to NixOS, but it worked as expected for me.

However I ran into problems when I tried to update the derivation to use PostgREST 0.4.0.0, downloading directly from their GitHub release:

```
with import <nixpkgs> {};
stdenv.mkDerivation {
  name = "patchedPostgrest";
  src = fetchurl {
    url = "https://github.com/begriffs/postgrest/releases/download/v0.4.0.0/postgrest-0.4.0.0-ubuntu.tar.xz";
    sha256 = "aa1756bffa4a81e3d6ce48509b8af7590dc06c2cab8b0e157a24bb6be9861e57";
  };
  # Work around the "unpacker appears to have produced no directories"
  # case that happens when the archive doesn't have a subdirectory.
  setSourceRoot = "sourceRoot=`pwd`";
  installPhase = ''
    mkdir -p $out/bin
    cp postgrest $out/bin/
    patchelf --set-interpreter \
      ${stdenv.glibc}/lib/ld-linux-x86-64.so.2 $out/bin/postgrest
    patchelf --set-rpath ${zlib}/lib:${postgresql.lib}/lib:${gmp}/lib:${stdenv.glibc}/lib:${stdenv.glibc}/lib $out/bin/postgrest
  '';
}
```

This builds with `nix-build patchedPostgrest.nix`, but running the binary fails:

```
result/bin/postgrest: result/bin/postgrest: no version information available (required by result/bin/postgrest)
result/bin/postgrest: symbol lookup error: result/bin/postgrest: undefined symbol: , version
```

Now I'm stuck. If you have time to help, I'd really appreciate it. If not, feel free to close this issue. Thanks again!

**Comment by NotBrianZach** [comment]
I'll look into it, I'm still using postgrest and will have to migrate to 4 myself eventually (only just now starting to wrap my head around compiling from source for larger haskell projects on nix/nixos (literally just fixed an error with a shell.nix in haskell project caused by stale dependencies in dynamic/shared libraries from non nix (I think) ghc/cabal install in ~/.ghc directory)). Super happy this was useful to someone. I think I'll try first to generate a .nix file to build the project from source first  (perhaps for v .4 git sha) and if that's too complicated, I'll see if I can work around this patching problem.

**Comment by NotBrianZach** [comment]
hopefully this will do it for ya 
https://github.com/begriffs/postgrest/pull/798

**Comment by jamesaoverton** [comment]
Worked for me. Much appreciated!
